import { Service } from "./service"

export class Services{
    dental_implants:Service = {
        service: "Dental Implants",
      imgSrc: "assets/dental-implants.png",
      content: ["Dental implants are a type of prosthesis that are used to replace missing teeth. They are designed to look and function like natural teeth, and are often used as an alternative to traditional dentures or bridges." ," One of the key advantages of dental implants is that they do not damage the neighbouring teeth. Traditional bridges, for example, require the adjacent teeth to be filed down in order to support the bridge. This can weaken those teeth and make them more prone to decay or other problems." ,"    Dental implants, on the other hand, are inserted directly into the jawbone, where they fuse with the bone over time. This provides a stable foundation for the replacement of tooth or teeth, without requiring any modifications to the surrounding teeth. " ,"    Overall, dental implants are considered to be a safe and effective option for tooth replacement, with a success rate of around 95%. They can improve both the function and appearance of your teeth, and can help to maintain the overall health of your mouth and jawbone.      "],
      youtube: "KaBMBtgo8so",
      route: "dental-implants"
    };

    aesthetic_dentistry:Service = {
        service: "Aesthetic Dentistry",
        imgSrc: "assets/aesthetic-dentistry.png",
        content: [ "Aesthetic or cosmetic dentistry is a specialized field of dentistry that focuses on improving the appearance of teeth, gums, and bite to enhance the overall aesthetics of a person's smile. It goes beyond traditional dentistry by not only addressing functional issues, such as improving the bite and restoring proper chewing function, but also improving the appearance of teeth to achieve a more attractive smile." ,"      Aesthetic or cosmetic dentistry procedures can include teeth whitening, veneers, dental bonding, dental implants, gum contouring, orthodontics (including clear aligners), and other treatments that help improve the appearance and function of the teeth and gums. These procedures are often used to correct cosmetic issues such as stained or discolored teeth, misaligned teeth, gaps between teeth, chipped or cracked teeth, and gum issues like uneven gum line or excessive gum display when smiling. " ,"      In addition to improving the appearance of the teeth and gums, aesthetic or cosmetic dentistry can also have a positive impact on a person's self-esteem and confidence. A beautiful smile can enhance a person's overall facial aesthetics and boost their self-image, leading to improved social interactions and increased self-assurance.Aesthetic or cosmetic dentistry should be approached with a comprehensive understanding of the patient's oral health, functional requirements, and aesthetic goals to achieve the best results."],
        youtube: "NdQunaRzeGY",
        route: "aesthetic-dentistry"
      };
      root_canal:Service ={
        service: "Root Canal Treatment",
        imgSrc: "assets/root-canal.png",
        content: ["Root canal treatment, also known as endodontic treatment, is a dental procedure that aims to save a tooth that is infected or abscessed. The procedure involves removing the inflamed or infected pulp, which is the soft tissue inside the tooth that contains nerves, blood vessels, and connective tissue. After the pulp is removed, the inside of the tooth is thoroughly cleaned and disinfected to remove any bacteria or debris. Finally, a filling material is used to seal the space and restore the tooth's structure and function. Root canal treatment is a common and effective way to relieve tooth pain and save teeth that might otherwise need to be extracted." ,"    1. \xA0 Prevents tooth loss: Root canal treatment can save a tooth from extraction. When the pulp, which contains nerves and blood vessels, becomes infected or damaged due to decay, trauma, or other factors, a root canal can remove the infected tissue and restore the tooth's health, allowing it to be retained in the mouth." ,"  2. \xA0    Prevents infection of neighboring teeth: An infected tooth can spread infection to neighboring teeth, leading to a more extensive dental problem. Root canal treatment removes the infected pulp, eliminating the source of infection and preventing it from spreading to other teeth." ,"   3. \xA0    Boosts the aesthetics of teeth: Root canals can help improve the appearance of a tooth. After the infected pulp is removed, the tooth can be restored with a dental crown, which can provide a natural-looking, aesthetically pleasing result, enhancing the appearance of the smile." ,"  4. \xA0    Prevents jawbone degeneration: Infected teeth can cause jawbone degeneration over time. Root canal treatment removes the infection, preventing further damage to the jawbone and preserving its integrity." ,"   5. \xA0    Boosts oral and overall health: Oral health is closely linked to overall health. Root canal treatment helps eliminate infection and inflammation in the tooth, which can have positive impacts on overall health. By saving the natural tooth, root canals also help maintain proper chewing and digestion, which is essential for overall well-being." ,"  6. \xA0    Virtually painless: Modern root canal procedures are generally well-tolerated and can be virtually painless. With the use of local anesthesia and advanced techniques, most patients experience minimal discomfort during and after the procedure." ,"      Overall, root canal treatment is a beneficial procedure that can save teeth from extraction, prevent infection and further dental problems, improve aesthetics, preserve jawbone health, boost oral and overall health, and be performed with minimal pain. It is considered a preferred option by patients and endodontists to address tooth infections and preserve natural teeth."] ,
        youtube: "14z8m0lnUog",
        route: "root-canal-treatment"
      };
      oral_surgery:Service = {
        service: "Oral Surgery",
        imgSrc: "assets/oral-surgery.png",
        content: ["Oral surgery is a specialized field of dentistry that involves the diagnosis and treatment of various conditions related to the teeth, gums, jaw, and other oral and facial structures. It encompasses a wide range of surgical procedures aimed at correcting oral and maxillofacial problems, such as tooth extractions, dental implant placement, Gum and bone surgeries, including tissue regeneration, bone augmentation, apical resection, perio-endo lesions, cyst, and abscess removal. These procedures are often performed under local anaesthesia or sedation to ensure patient comfort and safety during the surgery."], 
        youtube: undefined,
        route: "oral-surgery"
      }
      dentistry: Service = {
        service: "Dentistry For Kids",
        imgSrc: "assets/dentistry-for-kids.png",
        content: ["It is crucial for children to receive regular dental check-ups to prevent oral health problems and to promote good oral hygiene habits. We provide specialized care and can identify and treat dental problems in children, including tooth decay, gum disease, and orthodontic issues, as well as educate children and parents about proper dental hygiene practices, including brushing and flossing techniques and the importance of a healthy diet for good oral health.","Regular dental visits can also help to detect any potential problems early on, before they become more serious and require more extensive treatment. We provide preventive treatments such as fluoride treatments and dental sealants to help protect children's teeth from decay.","In addition to providing dental care, we also focus on creating a comfortable and positive environment for children during their dental visits. We understand that many children may feel anxious or fearful about visiting the dentist, and they work to create a welcoming and friendly atmosphere to help children feel at ease."," Overall, we play an essential role in promoting good oral health for children and ensuring that they receive the proper care and treatment they need to maintain healthy teeth and gums throughout childhood and into adulthood. " ],
        youtube: undefined,
        route: "dentistry-for-kids"
      };
      crowns: Service = {
        service: "Crowns, Bridges and Dentures",
        imgSrc: "assets/crowns.png",
        content: ["        Prosthodontic appliances are custom-made to fit the unique needs of each patient. They can be used to replace missing teeth, restore damaged teeth, and improve the appearance and function of teeth.Full and partial dentures are removable appliances that are used to replace missing teeth. They can be made of a variety of materials, including acrylic and porcelain, and are designed to fit securely in the mouth."," Crowns and bridges are fixed appliances that are used to restore damaged or missing teeth. A crown is a cap that is placed over a damaged tooth to protect it and restore its shape and function. A bridge is used to replace one or more missing teeth and is anchored to the adjacent teeth with crowns. ","        Night guards are used to treat TMJ disorder and sleep apnea by holding the jaw in a specific position to prevent snoring and other breathing problems during sleep. ","Overall, prosthodontics can provide effective solutions for a wide range of dental issues and help to improve the function and appearance of the teeth and mouth."," We at Thakur Dental Clinic are associated with some of the best dental labs in India. ","        Full mouth rehabilitation is a comprehensive dental treatment that involves the restoration or rebuilding of all or most of the teeth in the mouth. It may require the collaboration of different dental specialists, such as a general dentist, restorative dentist, periodontist, oral surgeon, orthodontist, and endodontist, to achieve the desired result. ", "The need for full mouth rehabilitation may arise due to various reasons, such as severe decay or trauma that has led to the loss of teeth, broken or fractured teeth, or teeth that have severely worn out due to a faulty biting pattern or tooth grinding. Additionally, ongoing complaints of jaw and muscle pain or headaches may require bite correction, which can be achieved through full mouth rehabilitation.", " It's important to note that full mouth rehabilitation is a highly personalized treatment, and the specific procedures involved will depend on the individual patient's needs and goals. The dental team will work together to develop a customized treatment plan that addresses the patient's unique concerns and aims to achieve a healthy, functional, and aesthetically pleasing smile."],
        route: "crowns-bridges-dentures",
        extraimages : ['assets/crown.png','assets/bridge.png','assets/dentures.png',],
        heading: 'Full Mouth Rehabilitation'
      }
      braces: Service = {
        service: "Braces and Aligners",
        imgSrc: "assets/braces.png",
        content: ["Dental braces are a common orthodontic treatment used to correct dental misalignments and improve oral health. Braces work by applying gentle, continuous pressure to the teeth and jaw, gradually moving them into their correct positions over time. ","There are several types of braces available, including traditional metal braces, ceramic braces, lingual braces, and clear aligners like Invisalign. Each type of brace has its own advantages and disadvantages, and the best option for an individual will depend on their specific dental needs and preferences."," In addition to improving the appearance of teeth, braces can also have significant health benefits. Straightening teeth can make it easier to clean them properly, reducing the risk of tooth decay, gum disease, and other oral health problems. Additionally, properly aligned teeth can improve bite function, reducing the risk of jaw pain, headaches, and other related issues."],
        route: "braces-and-aligners"
      }
      wisdom: Service = {
        service: "Wisdom Tooth Extraction",
        imgSrc: "assets/wisdom-tooth-extraction.png",
        content: ["Wisdom tooth extraction is a surgical procedure to remove one or more wisdom teeth — the four permanent adult teeth located at the back corners of your mouth on the top and bottom. ", " If a wisdom tooth doesn't have room to grow (impacted wisdom tooth), resulting in pain, infection or other dental problems, you'll likely need to have it pulled.  ", " Problems with impacted wisdom teeth ", " You'll likely need your impacted wisdom tooth pulled if it results in problems such as: ", " Pain ", " Trapping food and debris behind the wisdom tooth", "Infection or gum disease (periodontal disease)", " Tooth decay in a partially erupted wisdom tooth", " Damage to a nearby tooth or surrounding bone", "Development of a fluid-filled sac (cyst) around the wisdom tooth", "Complications with orthodontic treatments to straighten other teeth "],
        extraimages : ["assets/wisdom-tooth-extraction.png"],
        route: "wisdom-tooth-extraction"
      };
}