import { Service } from "./service"

export class Services{
    dental_implants:Service = {
        service: "Dental Implants",
      imgSrc: "assets/dental-implants.png",
      content: ["Dental implants are a type of prosthesis that are used to replace missing teeth. They are designed to look and function like natural teeth, and are often used as an alternative to traditional dentures or bridges." ," One of the key advantages of dental implants is that they do not damage the neighbouring teeth. Traditional bridges, for example, require the adjacent teeth to be filed down in order to support the bridge. This can weaken those teeth and make them more prone to decay or other problems." ,"    Dental implants, on the other hand, are inserted directly into the jawbone, where they fuse with the bone over time. This provides a stable foundation for the replacement of tooth or teeth, without requiring any modifications to the surrounding teeth. " ,"    Overall, dental implants are considered to be a safe and effective option for tooth replacement, with a success rate of around 95%. They can improve both the function and appearance of your teeth, and can help to maintain the overall health of your mouth and jawbone.      "],
      youtube: "KaBMBtgo8so",
      route: "dental-implants"
    };

    aesthetic_dentistry:Service = {
        service: "Aesthetic Dentistry",
        imgSrc: "assets/aesthetic-dentistry.png",
        content: [ "Aesthetic or cosmetic dentistry is a specialized field of dentistry that focuses on improving the appearance of teeth, gums, and bite to enhance the overall aesthetics of a person's smile. It goes beyond traditional dentistry by not only addressing functional issues, such as improving the bite and restoring proper chewing function, but also improving the appearance of teeth to achieve a more attractive smile." ,"      Aesthetic or cosmetic dentistry procedures can include teeth whitening, veneers, dental bonding, dental implants, gum contouring, orthodontics (including clear aligners), and other treatments that help improve the appearance and function of the teeth and gums. These procedures are often used to correct cosmetic issues such as stained or discolored teeth, misaligned teeth, gaps between teeth, chipped or cracked teeth, and gum issues like uneven gum line or excessive gum display when smiling. " ,"      In addition to improving the appearance of the teeth and gums, aesthetic or cosmetic dentistry can also have a positive impact on a person's self-esteem and confidence. A beautiful smile can enhance a person's overall facial aesthetics and boost their self-image, leading to improved social interactions and increased self-assurance.Aesthetic or cosmetic dentistry should be approached with a comprehensive understanding of the patient's oral health, functional requirements, and aesthetic goals to achieve the best results."],
        youtube: "NdQunaRzeGY",
        route: "aesthetic-dentistry"
      };
      root_canal:Service ={
        service: "Root Canal Treatment",
        imgSrc: "assets/root-canal.png",
        content: ["Root canal treatment, also known as endodontic treatment, is a dental procedure that aims to save a tooth that is infected or abscessed. The procedure involves removing the inflamed or infected pulp, which is the soft tissue inside the tooth that contains nerves, blood vessels, and connective tissue. After the pulp is removed, the inside of the tooth is thoroughly cleaned and disinfected to remove any bacteria or debris. Finally, a filling material is used to seal the space and restore the tooth's structure and function. Root canal treatment is a common and effective way to relieve tooth pain and save teeth that might otherwise need to be extracted." ,"    1. \xA0 Prevents tooth loss: Root canal treatment can save a tooth from extraction. When the pulp, which contains nerves and blood vessels, becomes infected or damaged due to decay, trauma, or other factors, a root canal can remove the infected tissue and restore the tooth's health, allowing it to be retained in the mouth." ,"  2. \xA0    Prevents infection of neighboring teeth: An infected tooth can spread infection to neighboring teeth, leading to a more extensive dental problem. Root canal treatment removes the infected pulp, eliminating the source of infection and preventing it from spreading to other teeth." ,"   3. \xA0    Boosts the aesthetics of teeth: Root canals can help improve the appearance of a tooth. After the infected pulp is removed, the tooth can be restored with a dental crown, which can provide a natural-looking, aesthetically pleasing result, enhancing the appearance of the smile." ,"  4. \xA0    Prevents jawbone degeneration: Infected teeth can cause jawbone degeneration over time. Root canal treatment removes the infection, preventing further damage to the jawbone and preserving its integrity." ,"   5. \xA0    Boosts oral and overall health: Oral health is closely linked to overall health. Root canal treatment helps eliminate infection and inflammation in the tooth, which can have positive impacts on overall health. By saving the natural tooth, root canals also help maintain proper chewing and digestion, which is essential for overall well-being." ,"  6. \xA0    Virtually painless: Modern root canal procedures are generally well-tolerated and can be virtually painless. With the use of local anesthesia and advanced techniques, most patients experience minimal discomfort during and after the procedure." ,"      Overall, root canal treatment is a beneficial procedure that can save teeth from extraction, prevent infection and further dental problems, improve aesthetics, preserve jawbone health, boost oral and overall health, and be performed with minimal pain. It is considered a preferred option by patients and endodontists to address tooth infections and preserve natural teeth."] ,
        youtube: "14z8m0lnUog",
        route: "root-canal-treatment"
      };
      oral_surgery:Service = {
        service: "Oral Surgery",
        imgSrc: "assets/oral-surgery.png",
        content: ["Root canal treatment, also known as endodontic treatment, is a dental procedure that aims to save a tooth that is infected or abscessed. The procedure involves removing the inflamed or infected pulp, which is the soft tissue inside the tooth that contains nerves, blood vessels, and connective tissue. After the pulp is removed, the inside of the tooth is thoroughly cleaned and disinfected to remove any bacteria or debris. Finally, a filling material is used to seal the space and restore the tooth's structure and function. Root canal treatment is a common and effective way to relieve tooth pain and save teeth that might otherwise need to be extracted." ,"      Prevents tooth loss: Root canal treatment can save a tooth from extraction. When the pulp, which contains nerves and blood vessels, becomes infected or damaged due to decay, trauma, or other factors, a root canal can remove the infected tissue and restore the tooth's health, allowing it to be retained in the mouth." ,"      Prevents infection of neighboring teeth: An infected tooth can spread infection to neighboring teeth, leading to a more extensive dental problem. Root canal treatment removes the infected pulp, eliminating the source of infection and preventing it from spreading to other teeth." ,"      Boosts the aesthetics of teeth: Root canals can help improve the appearance of a tooth. After the infected pulp is removed, the tooth can be restored with a dental crown, which can provide a natural-looking, aesthetically pleasing result, enhancing the appearance of the smile." ,"      Prevents jawbone degeneration: Infected teeth can cause jawbone degeneration over time. Root canal treatment removes the infection, preventing further damage to the jawbone and preserving its integrity." ,"      Boosts oral and overall health: Oral health is closely linked to overall health. Root canal treatment helps eliminate infection and inflammation in the tooth, which can have positive impacts on overall health. By saving the natural tooth, root canals also help maintain proper chewing and digestion, which is essential for overall well-being." ,"      Virtually painless: Modern root canal procedures are generally well-tolerated and can be virtually painless. With the use of local anesthesia and advanced techniques, most patients experience minimal discomfort during and after the procedure." ,"      Overall, root canal treatment is a beneficial procedure that can save teeth from extraction, prevent infection and further dental problems, improve aesthetics, preserve jawbone health, boost oral and overall health, and be performed with minimal pain. It is considered a preferred option by patients and endodontists to address tooth infections and preserve natural teeth." ],
        youtube: "KaBMBtgo8so",
        route: "oral-surgery"
      }
      dentistry: Service = {
        service: "Dentistry For Kids",
        imgSrc: "assets/dentistry-for-kids.png",
        content: ["Dental implants are a type of prosthesis that are used to replace missing teeth. They are designed to look and function like natural teeth, and are often used as an alternative to traditional dentures or bridges." ," One of the key advantages of dental implants is that they do not damage the neighbouring teeth. Traditional bridges, for example, require the adjacent teeth to be filed down in order to support the bridge. This can weaken those teeth and make them more prone to decay or other problems." ,"      Dental implants, on the other hand, are inserted directly into the jawbone, where they fuse with the bone over time. This provides a stable foundation for the replacement of tooth or teeth, without requiring any modifications to the surrounding teeth. " ,"      Overall, dental implants are considered to be a safe and effective option for tooth replacement, with a success rate of around 95%. They can improve both the function and appearance of your teeth, and can help to maintain the overall health of your mouth and jawbone.      "],
        youtube: "KaBMBtgo8so",
        route: "dentistry-for-kids"
      };
      crowns: Service = {
        service: "Crowns, Bridges and Dentures",
        imgSrc: "assets/crowns.png",
        content: ["Dental implants are a type of prosthesis that are used to replace missing teeth. They are designed to look and function like natural teeth, and are often used as an alternative to traditional dentures or bridges." ," One of the key advantages of dental implants is that they do not damage the neighbouring teeth. Traditional bridges, for example, require the adjacent teeth to be filed down in order to support the bridge. This can weaken those teeth and make them more prone to decay or other problems." ,"      Dental implants, on the other hand, are inserted directly into the jawbone, where they fuse with the bone over time. This provides a stable foundation for the replacement of tooth or teeth, without requiring any modifications to the surrounding teeth. " ,"      Overall, dental implants are considered to be a safe and effective option for tooth replacement, with a success rate of around 95%. They can improve both the function and appearance of your teeth, and can help to maintain the overall health of your mouth and jawbone.      "],
        youtube: "KaBMBtgo8so",
        route: "crowns-bridges-dentures"
      }
      braces: Service = {
        service: "Braces and Aligners",
        imgSrc: "assets/braces.png",
        content: ["Dental implants are a type of prosthesis that are used to replace missing teeth. They are designed to look and function like natural teeth, and are often used as an alternative to traditional dentures or bridges." ," One of the key advantages of dental implants is that they do not damage the neighbouring teeth. Traditional bridges, for example, require the adjacent teeth to be filed down in order to support the bridge. This can weaken those teeth and make them more prone to decay or other problems." ,"      Dental implants, on the other hand, are inserted directly into the jawbone, where they fuse with the bone over time. This provides a stable foundation for the replacement of tooth or teeth, without requiring any modifications to the surrounding teeth. " ,"      Overall, dental implants are considered to be a safe and effective option for tooth replacement, with a success rate of around 95%. They can improve both the function and appearance of your teeth, and can help to maintain the overall health of your mouth and jawbone.      "],
        youtube: "KaBMBtgo8so",
        route: "braces-and-aligners"
      }
      wisdom: Service = {
        service: "Wisdom Tooth Extraction",
        imgSrc: "assets/wisdom-tooth-extraction.png",
        content: ["Dental implants are a type of prosthesis that are used to replace missing teeth. They are designed to look and function like natural teeth, and are often used as an alternative to traditional dentures or bridges." ," One of the key advantages of dental implants is that they do not damage the neighbouring teeth. Traditional bridges, for example, require the adjacent teeth to be filed down in order to support the bridge. This can weaken those teeth and make them more prone to decay or other problems." ,"      Dental implants, on the other hand, are inserted directly into the jawbone, where they fuse with the bone over time. This provides a stable foundation for the replacement of tooth or teeth, without requiring any modifications to the surrounding teeth. " ,"      Overall, dental implants are considered to be a safe and effective option for tooth replacement, with a success rate of around 95%. They can improve both the function and appearance of your teeth, and can help to maintain the overall health of your mouth and jawbone.      "],
        youtube: "KaBMBtgo8so",
        route: "wisdom-tooth-extraction"
      };
}